"""add denormalised source column to jobs

Revision ID: fadfb559f5f9
Revises: d704963acc25
Created: 2026-09-21 05:11:49.339482+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "fadfb559f5f9"
down_revision: str | None = "d704963acc25"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("jobs", sa.Column("source", sa.String(length=40), nullable=False))
    op.create_index(op.f("ix_jobs_source"), "jobs", ["source"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_jobs_source"), table_name="jobs")
    op.drop_column("jobs", "source")
    # ### end Alembic commands ###
