"""company groups, aliases and source status

Revision ID: 5b46bd42c71c
Revises: ff8d67ba6027
Created: 2026-09-22 08:35:25.330447+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "5b46bd42c71c"
down_revision: str | None = "ff8d67ba6027"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Autogenerate proposed these four as NOT NULL with no default, which
    # PostgreSQL refuses on a table that already has rows. Server defaults
    # backfill the existing employers; they stay in place because the ORM does
    # not send these columns on every insert and a default is cheaper than
    # remembering to.
    #
    # `source_status` starts at 'manual' for everyone on purpose: it is the
    # honest answer until a scan or the verifier proves otherwise, and the
    # alternative — assuming 'live' — is exactly the claim §34 forbids.
    op.add_column("companies", sa.Column("parent_id", sa.String(length=80), nullable=True))
    op.add_column(
        "companies",
        sa.Column("aliases", sa.JSON(), nullable=False, server_default=sa.text("'[]'")),
    )
    op.add_column(
        "companies",
        sa.Column("country", sa.String(length=8), nullable=False, server_default=""),
    )
    op.add_column(
        "companies",
        sa.Column(
            "source_status", sa.String(length=16), nullable=False, server_default="manual"
        ),
    )
    op.add_column("companies", sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "companies",
        sa.Column("discovered_from", sa.String(length=40), nullable=False, server_default=""),
    )
    op.create_index(op.f("ix_companies_country"), "companies", ["country"], unique=False)
    op.create_index(op.f("ix_companies_parent_id"), "companies", ["parent_id"], unique=False)
    op.create_index(
        op.f("ix_companies_source_status"), "companies", ["source_status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_companies_source_status"), table_name="companies")
    op.drop_index(op.f("ix_companies_parent_id"), table_name="companies")
    op.drop_index(op.f("ix_companies_country"), table_name="companies")
    op.drop_column("companies", "discovered_from")
    op.drop_column("companies", "verified_at")
    op.drop_column("companies", "source_status")
    op.drop_column("companies", "country")
    op.drop_column("companies", "aliases")
    op.drop_column("companies", "parent_id")
    # ### end Alembic commands ###
