"""initial schema

Revision ID: d704963acc25
Revises:
Created: 2026-09-21 04:48:45.840411+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "d704963acc25"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("tier", sa.String(length=12), nullable=False),
        sa.Column("adapter", sa.String(length=40), nullable=True),
        sa.Column("adapter_arg", sa.String(length=200), nullable=True),
        sa.Column("careers_url", sa.Text(), nullable=False),
        sa.Column("industry", sa.String(length=80), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("open_roles", sa.Integer(), nullable=False),
        sa.Column("new_roles_7d", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_companies_adapter"), "companies", ["adapter"], unique=False)
    op.create_index(op.f("ix_companies_enabled"), "companies", ["enabled"], unique=False)
    op.create_index(op.f("ix_companies_industry"), "companies", ["industry"], unique=False)
    op.create_index(op.f("ix_companies_name"), "companies", ["name"], unique=False)
    op.create_index(op.f("ix_companies_tier"), "companies", ["tier"], unique=False)
    op.create_table(
        "provider_health",
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("target", sa.String(length=200), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("total_runs", sa.Integer(), nullable=False),
        sa.Column("total_failures", sa.Integer(), nullable=False),
        sa.Column("last_ok_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=False),
        sa.Column("backoff_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("capabilities", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_index(
        op.f("ix_provider_health_provider"), "provider_health", ["provider"], unique=False
    )
    op.create_index(op.f("ix_provider_health_state"), "provider_health", ["state"], unique=False)
    op.create_table(
        "runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("triggered_by", sa.String(length=40), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("providers_checked", sa.Integer(), nullable=False),
        sa.Column("providers_ok", sa.Integer(), nullable=False),
        sa.Column("companies_checked", sa.Integer(), nullable=False),
        sa.Column("postings_seen", sa.Integer(), nullable=False),
        sa.Column("postings_relevant", sa.Integer(), nullable=False),
        sa.Column("duplicates_merged", sa.Integer(), nullable=False),
        sa.Column("jobs_new", sa.Integer(), nullable=False),
        sa.Column("jobs_updated", sa.Integer(), nullable=False),
        sa.Column("jobs_closed", sa.Integer(), nullable=False),
        sa.Column("drafts_written", sa.Integer(), nullable=False),
        sa.Column("errors_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_runs_started_at"), "runs", ["started_at"], unique=False)
    op.create_index(op.f("ix_runs_status"), "runs", ["status"], unique=False)
    op.create_table(
        "saved_searches",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=300), nullable=False),
        sa.Column("query", sa.JSON(), nullable=False),
        sa.Column("pinned", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_builtin", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_saved_searches_pinned"), "saved_searches", ["pinned"], unique=False)
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=120), nullable=False),
        sa.Column("company_id", sa.String(length=80), nullable=True),
        sa.Column("company_name", sa.String(length=200), nullable=False),
        sa.Column("title", sa.String(length=400), nullable=False),
        sa.Column("title_normalized", sa.String(length=400), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("location_raw", sa.String(length=300), nullable=False),
        sa.Column("city", sa.String(length=120), nullable=False),
        sa.Column("country", sa.String(length=80), nullable=False),
        sa.Column("remote_policy", sa.String(length=16), nullable=False),
        sa.Column("employment_type", sa.String(length=24), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("posted_at", sa.Date(), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("removed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_open", sa.Boolean(), nullable=False),
        sa.Column("is_new", sa.Boolean(), nullable=False),
        sa.Column("times_seen", sa.Integer(), nullable=False),
        sa.Column("seniority", sa.String(length=16), nullable=False),
        sa.Column("experience_min_years", sa.Integer(), nullable=True),
        sa.Column("experience_max_years", sa.Integer(), nullable=True),
        sa.Column("language_requirement", sa.String(length=24), nullable=False),
        sa.Column("language_evidence", sa.String(length=400), nullable=False),
        sa.Column("salary_min", sa.Float(), nullable=True),
        sa.Column("salary_max", sa.Float(), nullable=True),
        sa.Column("salary_currency", sa.String(length=8), nullable=False),
        sa.Column("salary_period", sa.String(length=16), nullable=False),
        sa.Column("salary_annual_eur_min", sa.Float(), nullable=True),
        sa.Column("salary_annual_eur_max", sa.Float(), nullable=True),
        sa.Column("salary_basis", sa.String(length=12), nullable=False),
        sa.Column("salary_evidence", sa.String(length=400), nullable=False),
        sa.Column("skills", sa.JSON(), nullable=False),
        sa.Column("domains", sa.JSON(), nullable=False),
        sa.Column("role_category", sa.String(length=48), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("score_technical", sa.Integer(), nullable=False),
        sa.Column("score_experience", sa.Integer(), nullable=False),
        sa.Column("score_language", sa.Integer(), nullable=False),
        sa.Column("score_location", sa.Integer(), nullable=False),
        sa.Column("score_education", sa.Integer(), nullable=False),
        sa.Column("score_freshness", sa.Integer(), nullable=False),
        sa.Column("score_domain", sa.Integer(), nullable=False),
        sa.Column("match_reasons", sa.JSON(), nullable=False),
        sa.Column("match_gaps", sa.JSON(), nullable=False),
        sa.Column("flags", sa.JSON(), nullable=False),
        sa.Column("has_flags", sa.Boolean(), nullable=False),
        sa.Column("search_blob", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("status_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("applied_at", sa.Date(), nullable=True),
        sa.Column("follow_up_at", sa.Date(), nullable=True),
        sa.Column("contact_person", sa.String(length=200), nullable=False),
        sa.Column("salary_discussion", sa.Text(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("starred", sa.Boolean(), nullable=False),
        sa.Column("hidden", sa.Boolean(), nullable=False),
        sa.Column("draft_folder", sa.String(length=300), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_jobs_board", "jobs", ["is_open", "hidden", "posted_at", "score"], unique=False
    )
    op.create_index(op.f("ix_jobs_city"), "jobs", ["city"], unique=False)
    op.create_index(op.f("ix_jobs_company_id"), "jobs", ["company_id"], unique=False)
    op.create_index(op.f("ix_jobs_company_name"), "jobs", ["company_name"], unique=False)
    op.create_index(
        "ix_jobs_company_title", "jobs", ["company_name", "title_normalized"], unique=False
    )
    op.create_index(op.f("ix_jobs_country"), "jobs", ["country"], unique=False)
    op.create_index(op.f("ix_jobs_employment_type"), "jobs", ["employment_type"], unique=False)
    op.create_index(op.f("ix_jobs_follow_up_at"), "jobs", ["follow_up_at"], unique=False)
    op.create_index(op.f("ix_jobs_has_flags"), "jobs", ["has_flags"], unique=False)
    op.create_index(op.f("ix_jobs_hidden"), "jobs", ["hidden"], unique=False)
    op.create_index(op.f("ix_jobs_is_new"), "jobs", ["is_new"], unique=False)
    op.create_index(op.f("ix_jobs_is_open"), "jobs", ["is_open"], unique=False)
    op.create_index(
        op.f("ix_jobs_language_requirement"), "jobs", ["language_requirement"], unique=False
    )
    op.create_index("ix_jobs_pipeline", "jobs", ["status", "follow_up_at"], unique=False)
    op.create_index(op.f("ix_jobs_posted_at"), "jobs", ["posted_at"], unique=False)
    op.create_index(op.f("ix_jobs_remote_policy"), "jobs", ["remote_policy"], unique=False)
    op.create_index(op.f("ix_jobs_role_category"), "jobs", ["role_category"], unique=False)
    op.create_index(op.f("ix_jobs_salary_basis"), "jobs", ["salary_basis"], unique=False)
    op.create_index(op.f("ix_jobs_score"), "jobs", ["score"], unique=False)
    op.create_index(op.f("ix_jobs_seniority"), "jobs", ["seniority"], unique=False)
    op.create_index(op.f("ix_jobs_starred"), "jobs", ["starred"], unique=False)
    op.create_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
    op.create_index(op.f("ix_jobs_title_normalized"), "jobs", ["title_normalized"], unique=False)
    op.create_table(
        "run_providers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("target", sa.String(length=200), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("postings", sa.Integer(), nullable=False),
        sa.Column("requests_made", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("capabilities", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_run_providers_lookup", "run_providers", ["run_id", "state"], unique=False)
    op.create_index(op.f("ix_run_providers_provider"), "run_providers", ["provider"], unique=False)
    op.create_index(op.f("ix_run_providers_run_id"), "run_providers", ["run_id"], unique=False)
    op.create_index(op.f("ix_run_providers_state"), "run_providers", ["state"], unique=False)
    op.create_table(
        "job_sources",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.String(length=120), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("external_id", sa.String(length=300), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("posted_at", sa.Date(), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "provider", "external_id", name="uq_job_source"),
    )
    op.create_index(op.f("ix_job_sources_job_id"), "job_sources", ["job_id"], unique=False)
    op.create_index(op.f("ix_job_sources_provider"), "job_sources", ["provider"], unique=False)
    op.create_table(
        "status_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.String(length=120), nullable=False),
        sa.Column("from_status", sa.String(length=24), nullable=False),
        sa.Column("to_status", sa.String(length=24), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_status_events_at"), "status_events", ["at"], unique=False)
    op.create_index(op.f("ix_status_events_job_id"), "status_events", ["job_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_status_events_job_id"), table_name="status_events")
    op.drop_index(op.f("ix_status_events_at"), table_name="status_events")
    op.drop_table("status_events")
    op.drop_index(op.f("ix_job_sources_provider"), table_name="job_sources")
    op.drop_index(op.f("ix_job_sources_job_id"), table_name="job_sources")
    op.drop_table("job_sources")
    op.drop_index(op.f("ix_run_providers_state"), table_name="run_providers")
    op.drop_index(op.f("ix_run_providers_run_id"), table_name="run_providers")
    op.drop_index(op.f("ix_run_providers_provider"), table_name="run_providers")
    op.drop_index("ix_run_providers_lookup", table_name="run_providers")
    op.drop_table("run_providers")
    op.drop_index(op.f("ix_jobs_title_normalized"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_status"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_starred"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_seniority"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_score"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_salary_basis"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_role_category"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_remote_policy"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_posted_at"), table_name="jobs")
    op.drop_index("ix_jobs_pipeline", table_name="jobs")
    op.drop_index(op.f("ix_jobs_language_requirement"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_is_open"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_is_new"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_hidden"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_has_flags"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_follow_up_at"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_employment_type"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_country"), table_name="jobs")
    op.drop_index("ix_jobs_company_title", table_name="jobs")
    op.drop_index(op.f("ix_jobs_company_name"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_company_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_city"), table_name="jobs")
    op.drop_index("ix_jobs_board", table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_saved_searches_pinned"), table_name="saved_searches")
    op.drop_table("saved_searches")
    op.drop_index(op.f("ix_runs_status"), table_name="runs")
    op.drop_index(op.f("ix_runs_started_at"), table_name="runs")
    op.drop_table("runs")
    op.drop_index(op.f("ix_provider_health_state"), table_name="provider_health")
    op.drop_index(op.f("ix_provider_health_provider"), table_name="provider_health")
    op.drop_table("provider_health")
    op.drop_index(op.f("ix_companies_tier"), table_name="companies")
    op.drop_index(op.f("ix_companies_name"), table_name="companies")
    op.drop_index(op.f("ix_companies_industry"), table_name="companies")
    op.drop_index(op.f("ix_companies_enabled"), table_name="companies")
    op.drop_index(op.f("ix_companies_adapter"), table_name="companies")
    op.drop_table("companies")
    # ### end Alembic commands ###
