/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List and filter job postings */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One posting in full */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update your own fields
         * @description Update the fields a human owns.
         *
         *     A discovery run never writes these, so nothing here can be lost to a
         *     sweep. A status change is recorded in the history rather than only
         *     overwriting the current value.
         */
        patch: operations["patch_job_api_jobs__job_id__patch"];
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard overview and charts */
        get: operations["stats_api_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The company watchlist */
        get: operations["list_companies_api_companies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Company */
        get: operations["get_company_api_companies__company_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Discovery run history */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One run, provider by provider */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/searches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Searches */
        get: operations["list_searches_api_searches_get"];
        put?: never;
        /** Create Search */
        post: operations["create_search_api_searches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/searches/{search_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Search */
        delete: operations["delete_search_api_searches__search_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/searches/{search_id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run a saved search
         * @description Execute a saved search through exactly the same filter code as the
         *     listing endpoint, so a saved query can never behave differently from the
         *     query that created it.
         */
        get: operations["run_search_api_searches__search_id__results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rolling health of every source */
        get: operations["provider_health_api_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and database reachability */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ApplicationStatus
         * @enum {string}
         */
        ApplicationStatus: "new" | "reviewing" | "interested" | "to_apply" | "applied" | "interview" | "technical_interview" | "hr_interview" | "offer" | "rejected" | "withdrawn" | "expired" | "ignored";
        /** Charts */
        Charts: {
            /** By Day */
            by_day: components["schemas"]["DayCount"][];
            /** By Country */
            by_country: components["schemas"]["NamedCount"][];
            /** By Category */
            by_category: components["schemas"]["NamedCount"][];
            /** By Company */
            by_company: components["schemas"]["NamedCount"][];
            /** By Language */
            by_language: components["schemas"]["NamedCount"][];
            /** By Score Band */
            by_score_band: components["schemas"]["NamedCount"][];
        };
        /** CompanyOut */
        CompanyOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Tier */
            tier: string;
            /** Industry */
            industry: string;
            /** Adapter */
            adapter: string | null;
            /** Careers Url */
            careers_url: string;
            /** Enabled */
            enabled: boolean;
            /** Open Roles */
            open_roles: number;
            /** New Roles 7D */
            new_roles_7d: number;
            /** Last Checked At */
            last_checked_at: string | null;
            /**
             * Notes
             * @default
             */
            notes: string;
            /**
             * Is Automated
             * @default false
             */
            is_automated: boolean;
        };
        /** DayCount */
        DayCount: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Label */
            label: string;
            /** Age Days */
            age_days: number;
            /** Count */
            count: number;
        };
        /** Flag */
        Flag: {
            /** Code */
            code: string;
            /**
             * Why
             * @default
             */
            why: string;
            /**
             * Evidence
             * @default
             */
            evidence: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JobDetail
         * @description Everything about one posting, including its provenance and history.
         */
        JobDetail: {
            /** Id */
            id: string;
            /** Company Name */
            company_name: string;
            /** Company Id */
            company_id?: string | null;
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Location Raw */
            location_raw: string;
            /** City */
            city: string;
            /** Country */
            country: string;
            /** Remote Policy */
            remote_policy: string;
            /** Source */
            source: string;
            /**
             * Tier
             * @default normal
             */
            tier: string;
            /** Posted At */
            posted_at: string | null;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /** Age Days */
            age_days?: number | null;
            /** Is New */
            is_new: boolean;
            /** Is Open */
            is_open: boolean;
            /** Score */
            score: number;
            sub_scores: components["schemas"]["SubScores"];
            /**
             * Match Reasons
             * @default []
             */
            match_reasons: string[];
            /**
             * Match Gaps
             * @default []
             */
            match_gaps: string[];
            /**
             * Flags
             * @default []
             */
            flags: components["schemas"]["Flag"][];
            /** Seniority */
            seniority: string;
            /**
             * Seniority Label
             * @default
             */
            seniority_label: string;
            /** Experience Min Years */
            experience_min_years?: number | null;
            /** Language Requirement */
            language_requirement: string;
            /**
             * Language Label
             * @default
             */
            language_label: string;
            /**
             * Remote Label
             * @default
             */
            remote_label: string;
            salary: components["schemas"]["Salary"];
            /**
             * Skills
             * @default []
             */
            skills: string[];
            /**
             * Domains
             * @default []
             */
            domains: string[];
            /**
             * Role Category
             * @default
             */
            role_category: string;
            status: components["schemas"]["ApplicationStatus"];
            /** Starred */
            starred: boolean;
            /** Hidden */
            hidden: boolean;
            /** Applied At */
            applied_at?: string | null;
            /** Follow Up At */
            follow_up_at?: string | null;
            /**
             * Draft Folder
             * @default
             */
            draft_folder: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Summary
             * @default
             */
            summary: string;
            /**
             * Language Evidence
             * @default
             */
            language_evidence: string;
            /** Employment Type */
            employment_type: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Removed At */
            removed_at?: string | null;
            /**
             * Times Seen
             * @default 1
             */
            times_seen: number;
            /**
             * Notes
             * @default
             */
            notes: string;
            /**
             * Contact Person
             * @default
             */
            contact_person: string;
            /**
             * Salary Discussion
             * @default
             */
            salary_discussion: string;
            /**
             * Sources
             * @default []
             */
            sources: components["schemas"]["JobSourceOut"][];
            /**
             * History
             * @default []
             */
            history: components["schemas"]["StatusEventOut"][];
        };
        /** JobPage */
        JobPage: {
            /** Items */
            items: components["schemas"]["JobSummary"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * JobPatch
         * @description Only the fields a human owns. A discovery run never writes these.
         */
        JobPatch: {
            /** Starred */
            starred?: boolean | null;
            /** Hidden */
            hidden?: boolean | null;
            status?: components["schemas"]["ApplicationStatus"] | null;
            /** Notes */
            notes?: string | null;
            /** Contact Person */
            contact_person?: string | null;
            /** Salary Discussion */
            salary_discussion?: string | null;
            /** Applied At */
            applied_at?: string | null;
            /** Follow Up At */
            follow_up_at?: string | null;
            /** Status Note */
            status_note?: string | null;
        };
        /** JobSourceOut */
        JobSourceOut: {
            /** Provider */
            provider: string;
            /** External Id */
            external_id: string;
            /** Url */
            url: string;
            /** Posted At */
            posted_at: string | null;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Is Primary */
            is_primary: boolean;
        };
        /**
         * JobSummary
         * @description The listing row. Deliberately lighter than the detail view.
         */
        JobSummary: {
            /** Id */
            id: string;
            /** Company Name */
            company_name: string;
            /** Company Id */
            company_id?: string | null;
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Location Raw */
            location_raw: string;
            /** City */
            city: string;
            /** Country */
            country: string;
            /** Remote Policy */
            remote_policy: string;
            /** Source */
            source: string;
            /**
             * Tier
             * @default normal
             */
            tier: string;
            /** Posted At */
            posted_at: string | null;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /** Age Days */
            age_days?: number | null;
            /** Is New */
            is_new: boolean;
            /** Is Open */
            is_open: boolean;
            /** Score */
            score: number;
            sub_scores: components["schemas"]["SubScores"];
            /**
             * Match Reasons
             * @default []
             */
            match_reasons: string[];
            /**
             * Match Gaps
             * @default []
             */
            match_gaps: string[];
            /**
             * Flags
             * @default []
             */
            flags: components["schemas"]["Flag"][];
            /** Seniority */
            seniority: string;
            /**
             * Seniority Label
             * @default
             */
            seniority_label: string;
            /** Experience Min Years */
            experience_min_years?: number | null;
            /** Language Requirement */
            language_requirement: string;
            /**
             * Language Label
             * @default
             */
            language_label: string;
            /**
             * Remote Label
             * @default
             */
            remote_label: string;
            salary: components["schemas"]["Salary"];
            /**
             * Skills
             * @default []
             */
            skills: string[];
            /**
             * Domains
             * @default []
             */
            domains: string[];
            /**
             * Role Category
             * @default
             */
            role_category: string;
            status: components["schemas"]["ApplicationStatus"];
            /** Starred */
            starred: boolean;
            /** Hidden */
            hidden: boolean;
            /** Applied At */
            applied_at?: string | null;
            /** Follow Up At */
            follow_up_at?: string | null;
            /**
             * Draft Folder
             * @default
             */
            draft_folder: string;
        };
        /** NamedCount */
        NamedCount: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Count */
            count: number;
        };
        /** ProviderHealthOut */
        ProviderHealthOut: {
            /** Key */
            key: string;
            /** Provider */
            provider: string;
            /** Target */
            target: string;
            /** State */
            state: string;
            /** Consecutive Failures */
            consecutive_failures: number;
            /** Total Runs */
            total_runs: number;
            /** Total Failures */
            total_failures: number;
            /** Last Ok At */
            last_ok_at: string | null;
            /** Last Error At */
            last_error_at: string | null;
            /** Last Error */
            last_error: string;
            /** Backoff Until */
            backoff_until: string | null;
            /**
             * Capabilities
             * @default {}
             */
            capabilities: {
                [key: string]: unknown;
            };
            /**
             * Success Rate
             * @default 0
             */
            success_rate: number;
        };
        /** RunDetail */
        RunDetail: {
            /** Id */
            id: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Duration Ms */
            duration_ms: number;
            /** Status */
            status: string;
            /** Triggered By */
            triggered_by: string;
            /** Error */
            error: string;
            /** Providers Checked */
            providers_checked: number;
            /** Providers Ok */
            providers_ok: number;
            /** Companies Checked */
            companies_checked: number;
            /** Postings Seen */
            postings_seen: number;
            /** Postings Relevant */
            postings_relevant: number;
            /** Duplicates Merged */
            duplicates_merged: number;
            /** Jobs New */
            jobs_new: number;
            /** Jobs Updated */
            jobs_updated: number;
            /** Jobs Closed */
            jobs_closed: number;
            /** Drafts Written */
            drafts_written: number;
            /** Errors Count */
            errors_count: number;
            /**
             * Providers
             * @default []
             */
            providers: components["schemas"]["RunProviderOut"][];
        };
        /** RunOut */
        RunOut: {
            /** Id */
            id: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Duration Ms */
            duration_ms: number;
            /** Status */
            status: string;
            /** Triggered By */
            triggered_by: string;
            /** Error */
            error: string;
            /** Providers Checked */
            providers_checked: number;
            /** Providers Ok */
            providers_ok: number;
            /** Companies Checked */
            companies_checked: number;
            /** Postings Seen */
            postings_seen: number;
            /** Postings Relevant */
            postings_relevant: number;
            /** Duplicates Merged */
            duplicates_merged: number;
            /** Jobs New */
            jobs_new: number;
            /** Jobs Updated */
            jobs_updated: number;
            /** Jobs Closed */
            jobs_closed: number;
            /** Drafts Written */
            drafts_written: number;
            /** Errors Count */
            errors_count: number;
        };
        /** RunProviderOut */
        RunProviderOut: {
            /** Provider */
            provider: string;
            /** Target */
            target: string;
            /** State */
            state: string;
            /** Postings */
            postings: number;
            /** Requests Made */
            requests_made: number;
            /** Duration Ms */
            duration_ms: number;
            /** Error */
            error: string;
            /**
             * Capabilities
             * @default {}
             */
            capabilities: {
                [key: string]: unknown;
            };
        };
        /**
         * Salary
         * @description Two figures with different meanings, kept apart on purpose.
         *
         *     ``amount_*`` is exactly what the posting printed. ``annual_eur_*`` is
         *     annualised and converted, so it is always derived -- ``is_derived`` says
         *     when, and the interface marks those with a "≈".
         */
        Salary: {
            basis: components["schemas"]["SalaryBasis"];
            /** Amount Min */
            amount_min?: number | null;
            /** Amount Max */
            amount_max?: number | null;
            /**
             * Currency
             * @default
             */
            currency: string;
            /**
             * Period
             * @default
             */
            period: string;
            /** Annual Eur Min */
            annual_eur_min?: number | null;
            /** Annual Eur Max */
            annual_eur_max?: number | null;
            /**
             * Evidence
             * @default
             */
            evidence: string;
            /**
             * Display
             * @default
             */
            display: string;
            /**
             * Is Derived
             * @default false
             */
            is_derived: boolean;
        };
        /**
         * SalaryBasis
         * @description Where a salary figure came from. Never let an estimate be displayed as
         *     if the employer stated it.
         * @enum {string}
         */
        SalaryBasis: "explicit" | "estimated" | "unknown";
        /** SavedSearchIn */
        SavedSearchIn: {
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Query
             * @default {}
             */
            query: {
                [key: string]: unknown;
            };
            /**
             * Pinned
             * @default false
             */
            pinned: boolean;
        };
        /** SavedSearchOut */
        SavedSearchOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Query */
            query: {
                [key: string]: unknown;
            };
            /** Pinned */
            pinned: boolean;
            /** Is Builtin */
            is_builtin: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** Stats */
        Stats: {
            /** Found Today */
            found_today: number;
            /** New Since Last Run */
            new_since_last_run: number;
            /** High Match */
            high_match: number;
            /** Total Open */
            total_open: number;
            /** Applications Pending */
            applications_pending: number;
            /** Applications Submitted */
            applications_submitted: number;
            /** Companies With Roles */
            companies_with_roles: number;
            /** Average Match Score */
            average_match_score: number;
            /** Max Age Days */
            max_age_days: number;
            /** Headline */
            headline: string;
            charts: components["schemas"]["Charts"];
            last_run: components["schemas"]["RunOut"] | null;
            /** Next Run At */
            next_run_at: string | null;
            /**
             * Watchlist
             * @default []
             */
            watchlist: components["schemas"]["CompanyOut"][];
        };
        /** StatusEventOut */
        StatusEventOut: {
            /** From Status */
            from_status: string;
            /** To Status */
            to_status: string;
            /** Note */
            note: string;
            /**
             * At
             * Format: date-time
             */
            at: string;
        };
        /** SubScores */
        SubScores: {
            /** Technical */
            technical: number;
            /** Experience */
            experience: number;
            /** Language */
            language: number;
            /** Location */
            location: number;
            /** Education */
            education: number;
            /** Freshness */
            freshness: number;
            /** Domain */
            domain: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                /** @description Free text over company, title, city and skills */
                q?: string | null;
                /** @description dream, high or normal */
                tier?: string | null;
                country?: ("de" | "ch" | "at" | "nl" | "eu") | null;
                city?: string | null;
                company?: string | null;
                /** @description Role category, e.g. 'Computer Vision' */
                category?: string | null;
                /** @description Language requirement level */
                language?: string | null;
                source?: string | null;
                status?: components["schemas"]["ApplicationStatus"] | null;
                domain?: string | null;
                /** @description remote, hybrid, onsite or unknown */
                remote?: string | null;
                seniority?: string | null;
                min_score?: number | null;
                max_age_days?: number | null;
                salary_min?: number | null;
                only_new?: boolean;
                only_starred?: boolean;
                /** @description Hide anything carrying a warning flag */
                only_clean?: boolean;
                include_hidden?: boolean;
                include_closed?: boolean;
                sort?: "newest" | "score" | "company" | "discovered" | "salary";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_job_api_jobs__job_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stats_api_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stats"];
                };
            };
        };
    };
    list_companies_api_companies_get: {
        parameters: {
            query?: {
                tier?: string | null;
                /** @description true for employers with a readable endpoint, false for the manual watchlist */
                automated?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_company_api_companies__company_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_searches_api_searches_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedSearchOut"][];
                };
            };
        };
    };
    create_search_api_searches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavedSearchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedSearchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_search_api_searches__search_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                search_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_search_api_searches__search_id__results_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                search_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    provider_health_api_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderHealthOut"][];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
