"""Runtime settings, owned by the user rather than by a file.

The profile started as ``config/profile.yml``, which meant changing a
preference required a text editor and a container restart. That is fine for a
script and disqualifying for a product, so the document now lives here and the
YAML is demoted to a seed: it supplies the defaults on first boot and is never
read again.

One row, holding the whole profile as JSON. A settings document is read on
every scan and written rarely, by one person; splitting it into columns would
buy nothing and cost a migration every time a preference is added.
"""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import JSON, Boolean, DateTime, Integer, String
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base, utcnow

SETTINGS_ID = 1


class AppSettings(Base):
    __tablename__ = "app_settings"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, default=SETTINGS_ID)

    #: The profile document, same shape as config/profile.example.yml.
    profile: Mapped[dict] = mapped_column(JSON, default=dict)

    #: False until onboarding finishes, which is what the app checks to decide
    #: whether to show the wizard or the dashboard.
    onboarded: Mapped[bool] = mapped_column(Boolean, default=False)

    #: Where the seed came from, so it is obvious later whether these values
    #: were configured by a person or inherited from the shipped example.
    seeded_from: Mapped[str] = mapped_column(String(200), default="")

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=utcnow, onupdate=utcnow
    )


class Notification(Base):
    """Something worth telling the user about, generated by a scan.

    Stored rather than derived on read so that "seen" is meaningful: a
    high-match role found at 03:00 should still be waiting at 09:00, and
    should stop being new once it has been looked at.
    """

    __tablename__ = "notifications"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    #: high_match | dream_company | run_failed | job_closed | follow_up_due
    kind: Mapped[str] = mapped_column(String(32), index=True)
    title: Mapped[str] = mapped_column(String(300))
    body: Mapped[str] = mapped_column(String(600), default="")
    #: Where clicking it should go.
    href: Mapped[str] = mapped_column(String(400), default="")
    severity: Mapped[str] = mapped_column(String(16), default="info")
    job_id: Mapped[str | None] = mapped_column(String(120), nullable=True)
    company_id: Mapped[str | None] = mapped_column(String(80), nullable=True)
    read_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=utcnow, index=True
    )

    #: Stops a repeating condition producing the same notification hourly.
    dedupe_key: Mapped[str] = mapped_column(String(200), default="", index=True)
