"use client";

import { useState } from "react";
import Link from "next/link";
import { Bell, CheckCheck } from "lucide-react";
import { api, type NotificationOut } from "@/lib/api";
import { useResource } from "@/lib/hooks";
import { Button } from "@/components/ui/primitives";
import { cn, relativeTime } from "@/lib/utils";

const SEVERITY_DOT: Record<string, string> = {
  success: "bg-ok",
  warning: "bg-warn",
  danger: "bg-danger",
  info: "bg-info",
  muted: "bg-muted-foreground",
};

/**
 * The notification bell.
 *
 * Reads the same store the overview feed does, so the two can never disagree
 * about what happened. Every entry was generated by a scan from rows it
 * actually wrote — there are no synthetic "welcome" notifications.
 */
export function NotificationBell() {
  const [open, setOpen] = useState(false);
  const { data, refresh } = useResource(() => api.notifications(20), [], {
    pollMs: 60_000,
  });

  const unread = data?.unread ?? 0;

  async function markAll() {
    try {
      await api.markAllRead();
      void refresh(true);
    } catch {
      /* the badge simply stays until the next poll */
    }
  }

  return (
    <div className="relative">
      <Button
        variant="ghost"
        size="icon"
        onClick={() => setOpen((v) => !v)}
        aria-label={unread ? `${unread} unread notifications` : "Notifications"}
        aria-expanded={open}
      >
        <Bell />
        {unread > 0 && (
          <span className="absolute right-1 top-1 flex size-[7px]">
            <span className="absolute inline-flex size-full rounded-full bg-info opacity-70" />
            <span className="relative inline-flex size-[7px] rounded-full bg-info" />
          </span>
        )}
      </Button>

      {open && (
        <>
          <div className="fixed inset-0 z-40" onClick={() => setOpen(false)} aria-hidden />
          <div className="absolute right-0 top-9 z-50 w-[22rem] overflow-hidden rounded-lg border border-border bg-popover shadow-xl">
            <div className="flex items-center justify-between border-b border-border px-3 py-2">
              <span className="text-[12px] font-medium">Notifications</span>
              {unread > 0 && (
                <button
                  onClick={markAll}
                  className="flex items-center gap-1 text-[11px] text-muted-foreground hover:text-foreground"
                >
                  <CheckCheck className="size-3" />
                  Mark all read
                </button>
              )}
            </div>

            <div className="max-h-[22rem] overflow-y-auto scrollbar-thin">
              {!data?.items.length ? (
                <p className="px-3 py-8 text-center text-[11px] text-muted-foreground">
                  Nothing yet. Notifications appear when a scan finds something worth
                  telling you about.
                </p>
              ) : (
                data.items.map((item) => (
                  <NotificationRow key={item.id} item={item} onNavigate={() => setOpen(false)} />
                ))
              )}
            </div>
          </div>
        </>
      )}
    </div>
  );
}

function NotificationRow({
  item,
  onNavigate,
}: {
  item: NotificationOut;
  onNavigate: () => void;
}) {
  const body = (
    <>
      <span
        className={cn(
          "mt-1.5 size-1.5 shrink-0 rounded-full",
          SEVERITY_DOT[item.severity] ?? "bg-muted-foreground",
        )}
      />
      <span className="min-w-0 flex-1">
        <span className="block text-[12px] leading-snug">{item.title}</span>
        {item.body && (
          <span className="mt-0.5 block text-[11px] leading-snug text-muted-foreground">
            {item.body}
          </span>
        )}
        <span className="mt-1 block text-[10px] text-muted-foreground/70">
          {relativeTime(item.created_at)}
        </span>
      </span>
    </>
  );

  const className = cn(
    "flex w-full gap-2.5 border-b border-border px-3 py-2.5 text-left transition-colors last:border-0 hover:bg-accent",
    !item.read_at && "bg-info-soft/30",
  );

  if (!item.href) return <div className={className}>{body}</div>;

  return (
    <Link
      href={item.href}
      onClick={() => {
        onNavigate();
        void api.markRead(item.id).catch(() => {});
      }}
      className={className}
    >
      {body}
    </Link>
  );
}
