import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({
  baseDirectory: dirname(fileURLToPath(import.meta.url)),
});

const config = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      // Generated by Next.js on every build; its triple-slash references are
      // required and must not be linted.
      "next-env.d.ts",
      // Generated from the API's OpenAPI document by `npm run generate:types`.
      "lib/api-types.ts",
    ],
  },
];

export default config;
